### ISSUE TITLE
Client not working with tuiodroid android app

### ISSUE THREAD

**Issue by rjx-ray** [Iwanaka/ofxTuio#1]
The android app works very briefly when first started but then hangs.
Looking at the OSC layer is sends messages with incrementing sequence numbers up to 72 and then stops, it seems like its waiting for some response/
Any ideas?

**Comment by Iwanaka** [comment]
Hi rjx-ray.
Thank you for your report.

hmm... I can't check to that problem because Tuiodoroid dose not work correctry on my Android phone.
Can I see error code on your project ?

**Comment by rjx-ray** [comment]
I believe its a problem with the droid app. I've now tried many different clients  with it. There's never any error code, it just stops sending after sequence number 72 saying host unreachable . If I restart it it, it sends another 72 messages and stops again.

As far as I know there is no acknowledgement requires for TUIO messages , is that right?

Can you recommend any other test server for your client? I need something that can emulate multitouch gestures

**Comment by Iwanaka** [comment]
> As far as I know there is no acknowledgement requires for TUIO messages , is that right?

Yes it is right. there is no acknowledgement messages. Just only sending.

> Can you recommend any other test server for your client?

How about these.

TUIO-Simulator. 
It does working on Windows OS or Mac OS.
It's not very intuitive if you use mouse, but it support to multi touch gestures.
https://unitylist.com/p/3gm/TUIO-Simulator

ZIG SIM
This app working on IOS or Android.
You can use multi touch gestures intuitive more than above app.
(and more functions. accel, gyro, pressure... It's so fun!)
But It is not support to TUIO protocol.
You need to format to messages from ZIGSIM to TUIO.
https://zig-project.com/

**Comment by Iwanaka** [comment]
I could confirm to work correctly TUIOdoroid on my Android phone.
And I tried send messages to a app using my ofxTUIO client.
It seems like good working... There was no happened any errors.
Client : Windows10, Openframeworks 11.0, ofxTUIO
Server : Android8.0.0, TUIOdoroid
![test](https://user-images.githubusercontent.com/16041381/81390016-b8fc1f80-9155-11ea-909d-9a9902604265.gif)
